name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use node 12.14.1
        uses: actions/setup-node@v1
        with:
          node-version: "12.14.1"
      - run: npm ci
      - run: npm run compile
      - run: npm run lint
      - run: npm test
